# Generated by Django 5.2.3 on 2025-06-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='date',
        ),
    ]
