# Generated by Django 5.2.3 on 2025-06-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('mapping', '0002_remove_mapping_date'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapping',
            unique_together={('patient', 'doctor')},
        ),
    ]
